[env]
TARGET_DIR = "target/debug"


[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-dev]
dependencies = ["format"]
command = "cargo"
args = ["build"]

[tasks.start-dev]
dependencies = ["format"]
command = "cargo"
args = ["run"]


# Since environment variables in tasks are set after dependencies run
[tasks.env-prod]
env = { TARGET_DIR = "target/release" }

[tasks.build-prod]
dependencies = ["env-prod"]
command = "cargo"
args = ["build", "-r"]

[tasks.start-prod]
dependencies = ["env-prod"]
command = "cargo"
args = ["run", "-r"]
env = { TARGET_DIR = "target/release" }
