[env]
TARGET_DIR = "target/debug"


[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.move-libs]
script_runner = "@duckscript"
script = '''
libs = glob_array ./libs/vosk/*.*
for path in ${libs}
    fname = basename ${path}
    echo ${fname}
    cp ./${path} ./${TARGET_DIR}/${fname}
end
'''


[tasks.build-dev]
dependencies = ["format"]
command = "cargo"
args = ["build"]

[tasks.start-dev]
dependencies = ["format", "move-libs"]
command = "cargo"
args = ["run"]


# Since environment variables in tasks are set after dependencies run
[tasks.env-prod]
env = { TARGET_DIR = "target/release" }

[tasks.build-prod]
dependencies = ["env-prod"]
command = "cargo"
args = ["build", "-r"]

[tasks.start-prod]
dependencies = ["env-prod", "move-libs"]
command = "cargo"
args = ["run", "-r"]
env = { TARGET_DIR = "target/release" }
